version: '3'

services:
  main-service:
    build:
      context: .
      dockerfile: main-services/Dockerfile
      args:
        pg_host: pgdbgames
        pg_host1: pgdbusers
    image: main-api
    ports:
      - 8080:8080
    links:
      - pgdbgames
      - pgdbusers
    depends_on:
      - pgdbgames
      - pgdbusers

  analysis-service:
    build:
      context: .
      dockerfile: analysis-services/Dockerfile
      args:
        pg_host: pg
    image: analysis-api
    ports:
      - 8090:8090
    links:
      - pgdbgames
      - pgdbusers
    depends_on:
      - pgdbgames
      - pgdbusers

  pgdbgames:
    image: postgres
    shm_size: 512m
    command: postgres -c plan_cache_mode=force_custom_plan
    environment:
      - POSTGRES_DB=cloudapi
      - POSTGRES_USER=cloudapi
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql1/data

  pgdbusers:
    image: postgres
    shm_size: 512m
    command: postgres -c plan_cache_mode=force_custom_plan
    environment:
      - POSTGRES_DB=cloudapi
      - POSTGRES_USER=cloudapi
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
    volumes:
      - pg1:/var/lib/postgresql2/data

volumes:
  pg:
  pg1: